# Alembic Configuration File

[alembic]
sqlalchemy.url = driver://user:password@localhost/dbname
script_location = alembic
prepend_sys_path = .
sqlalchemy.echo = false

[logging]
keys = root,sqlalchemy
handlers = console
qualname = sqlalchemy.engine

[formatters]
keys = generic
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

[logging_root]
level = WARN
handlers = console

[logging_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
